/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PatientManagementSystem.View.Secretary;

import PatientManagementSystem.View.EventSystem.Event;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Shem
 */
public class ViewSecretaryMainMenu extends javax.swing.JFrame {

    public Event onSelectIndex, onApproveRequest, onRejectRequest, onLogOut,
            onSeeMedicineStock, onRemovePatient, onSeeDoctorAvailability;
    
    /**
     * Creates new form SecretaryMainMenu
     */
    public ViewSecretaryMainMenu() {
        initComponents();
        onSelectIndex = new Event();
        onApproveRequest = new Event();
        onRejectRequest = new Event();
        onLogOut = new Event();
        onSeeMedicineStock = new Event();
        onRemovePatient = new Event();
        onSeeDoctorAvailability = new Event();
    }
    
    int validIndex = -1;
    
    public void fillRequestList(ArrayList<String> requests) {
        
        DefaultListModel listModel = new DefaultListModel();
        
        for (int i = 0; i < requests.size(); i++) 
        {
            listModel.addElement(requests.get(i));            
        }
        
        lstRequests.setModel(listModel);
    }
    
    public void setRequestDescription(String text) {
        txtRequestDescription.setText(text);
    }
    
    public int getSelectedRequestId() {
        if (lstRequests.getSelectedIndex() > -1)
        {
            validIndex = lstRequests.getSelectedIndex();  
            return lstRequests.getSelectedIndex();            
        }
        else if (validIndex > -1){
            return validIndex;
        }
        
        return -1;
    }
    
    public void clearDescriptionText() {
        txtRequestDescription.setText("");
    }
    
    public void enableButtons(boolean isEnabled)  {
        btnApproveRequest.setEnabled(isEnabled);
        btnRejectRequest.setEnabled(isEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRequests = new javax.swing.JList<>();
        lblPatientRequests = new javax.swing.JLabel();
        btnApproveRequest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRequestDescription = new javax.swing.JTextArea();
        lblRequestDescription = new javax.swing.JLabel();
        btnRejectRequest = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnMedicineStock = new javax.swing.JButton();
        btnRemovePatient = new javax.swing.JButton();
        btnDoctorAvailability = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lstRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstRequests);

        lblPatientRequests.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPatientRequests.setText("Patient requests");

        btnApproveRequest.setText("Approve request");
        btnApproveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRequestActionPerformed(evt);
            }
        });

        txtRequestDescription.setEditable(false);
        txtRequestDescription.setColumns(20);
        txtRequestDescription.setRows(5);
        jScrollPane2.setViewportView(txtRequestDescription);

        lblRequestDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRequestDescription.setText("Request description");

        btnRejectRequest.setText("Reject request");
        btnRejectRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectRequestActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnMedicineStock.setText("Medicine stock");
        btnMedicineStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineStockActionPerformed(evt);
            }
        });

        btnRemovePatient.setText("Remove patient");
        btnRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePatientActionPerformed(evt);
            }
        });

        btnDoctorAvailability.setText("Doctor availablity");
        btnDoctorAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorAvailabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientRequests)
                            .addComponent(lblRequestDescription))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDoctorAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRejectRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemovePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMedicineStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApproveRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPatientRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRequestDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproveRequest)
                    .addComponent(btnRejectRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedicineStock)
                    .addComponent(btnRemovePatient)
                    .addComponent(btnDoctorAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRequestsMouseClicked
        onSelectIndex.invoke();
    }//GEN-LAST:event_lstRequestsMouseClicked

    private void btnApproveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRequestActionPerformed
        onApproveRequest.invoke();
    }//GEN-LAST:event_btnApproveRequestActionPerformed

    private void btnRejectRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectRequestActionPerformed
        onRejectRequest.invoke();
    }//GEN-LAST:event_btnRejectRequestActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        onLogOut.invoke();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDoctorAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorAvailabilityActionPerformed
        onSeeDoctorAvailability.invoke();
    }//GEN-LAST:event_btnDoctorAvailabilityActionPerformed

    private void btnRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePatientActionPerformed
        onRemovePatient.invoke();
    }//GEN-LAST:event_btnRemovePatientActionPerformed

    private void btnMedicineStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineStockActionPerformed
        onSeeMedicineStock.invoke();
    }//GEN-LAST:event_btnMedicineStockActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSecretaryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSecretaryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSecretaryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSecretaryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSecretaryMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveRequest;
    private javax.swing.JButton btnDoctorAvailability;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMedicineStock;
    private javax.swing.JButton btnRejectRequest;
    private javax.swing.JButton btnRemovePatient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPatientRequests;
    private javax.swing.JLabel lblRequestDescription;
    private javax.swing.JList<String> lstRequests;
    private javax.swing.JTextArea txtRequestDescription;
    // End of variables declaration//GEN-END:variables
}
